services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    environment:
      USER: ${ODOO_USER}
      PASSWORD: ${ODOO_PASSWORD}
    ports:
      - 8069:8069
    volumes:
      - ./odoo/addons:/mnt/extra-addons
  db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      ODOO_USER: ${ODOO_USER}
      ODOO_PASSWORD: ${ODOO_PASSWORD}
      BACKEND_USER: ${BACKEND_USER}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD}
      BACKEND_DB: ${BACKEND_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./odoo/init/init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
