package dev.hekmyr.holidays.api.model;

public enum ErrorCodes {
    EMAIL_ALREADY_EXISTS,
    WEAK_PASSWORD,
    PASSWORD_MISMATCH,
    ODOO_ERROR,
    RESPONSE_NOT_OK,
    NOT_FOUND,
    TOO_MANY_GUEST,
    NO_DATE_PROVIDED,
    END_DATE_BEFORE_START,
    TOO_SHORT_DURATION,
    PAYMENT_FAILED,
    UNKNOWN;
}
