#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ODOO_USER WITH PASSWORD '$ODOO_PASSWORD' CREATEDB;
    GRANT ALL ON SCHEMA public TO $ODOO_USER;
    CREATE USER $BACKEND_USER WITH PASSWORD '$BACKEND_PASSWORD';
    GRANT ALL ON SCHEMA public TO $BACKEND_USER;
    CREATE DATABASE $BACKEND_DB;
    GRANT ALL ON DATABASE $BACKEND_DB TO $BACKEND_USER;
EOSQL
